-- https://school.programmers.co.kr/learn/courses/30/lessons/131537
-- 20M / AI(support)
-- 1.UNION은 중복 제거하니까 UNION ALL로 모두 합치기 2.UNION은 COLUMN수 맞춰야 함
(SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE >='2022-03-01' AND  SALES_DATE <'2022-04-01')
UNION ALL
(SELECT DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE >='2022-03-01' AND  SALES_DATE <'2022-04-01')

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID
