-- https://school.programmers.co.kr/learn/courses/30/lessons/131120

SELECT MONTH(DATE_OF_BIRTH),YEAR(DATE_OF_BIRTH),TO_CHAR(DATE_OF_BIRTH,'yyyy-mm-dd'),MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS 'DATE_OF_BIRTH'
FROM MEMBER_PROFILE 
WHERE MONTH(DATE_OF_BIRTH) = '3' && GENDER = 'W' && IFNULL(TLNO,'NULL') != 'NULL'
ORDER BY 'MEMBER_ID';
