-- https://school.programmers.co.kr/learn/courses/30/lessons/157340
-- 12M

SELECT T.CAR_ID, CASE WHEN SUM(AV) > 0 THEN '대여중'
    ELSE '대여 가능' END AS 'AVAILABILITY'
FROM
(SELECT 
    CAR_ID, 
    CASE WHEN START_DATE <='2022-10-16' AND END_DATE >= '2022-10-16' THEN 1
    ELSE 0 END AS 'AV'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) T
GROUP BY T.CAR_ID
ORDER BY T.CAR_ID DESC;
