-- https://school.programmers.co.kr/learn/courses/30/lessons/157340
-- 12M
-- START_DATE <='2022-10-16' AND END_DATE >= '2022-10-16' == '2022-10-16' BETWEEN START_DATE AND END_DATE

SELECT CAR_ID, CASE WHEN SUM(
    CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN 1
    ELSE 0 END
    ) > 0 THEN '대여중'
    ELSE '대여 가능' END AS 'AVAILABILITY'

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;



-- 초안 (서브쿼리 사용)
-- SELECT T.CAR_ID, CASE WHEN SUM(AV) > 0 THEN '대여중'
--     ELSE '대여 가능' END AS 'AVAILABILITY'
-- FROM
-- (SELECT 
--     CAR_ID, 
--     CASE WHEN START_DATE <='2022-10-16' AND END_DATE >= '2022-10-16' THEN 1
--     ELSE 0 END AS 'AV'
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) T
-- GROUP BY T.CAR_ID
-- ORDER BY T.CAR_ID DESC;
