-- https://school.programmers.co.kr/learn/courses/30/lessons/151139
-- 17M / AI(SUPPORT)
-- 1.N회 이상 그룹 구하려면 'IN 서브쿼리' 전략 사용해도 좋음

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE>='2022-08-01' AND START_DATE<'2022-11-01'
    AND CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE>='2022-08-01' AND START_DATE<'2022-11-01' 
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5    
    )
GROUP BY MONTH, CAR_ID

ORDER BY MONTH, CAR_ID DESC; 
