-- https://school.programmers.co.kr/learn/courses/30/lessons/164670
-- 13M / AI(HINT)
-- 1.SUBSTRING(칼럼,시작IDX,길이) 2.CONCAT은 PARAMETER수 제한X

SELECT U.USER_ID, U.NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS '전체주소', CONCAT(SUBSTRING(U.TLNO,1,3),'-',SUBSTRING(U.TLNO,4,4),'-',SUBSTRING(U.TLNO,8,4)) AS '전화번호'
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID
HAVING COUNT(*) >= 3
ORDER BY U.USER_ID DESC;
