-- https://school.programmers.co.kr/learn/courses/30/lessons/164671
-- 9M
-- 1.서브쿼리로도 구현할 수 있음

-- 서브쿼리
SELECT CONCAT('/home/grep/src/',B.BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH 
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
WHERE B.VIEWS = (
    SELECT VIEWS
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
    )
ORDER BY F.FILE_ID DESC;

-- -- 삼중 조인
-- SELECT CONCAT('/home/grep/src/',B.BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) AS FILE_PATH 
-- FROM USED_GOODS_BOARD B
-- JOIN USED_GOODS_FILE F ON B.BOARD_ID = F.BOARD_ID
-- JOIN 
-- (SELECT MAX(VIEWS) AS VIEW
-- FROM USED_GOODS_BOARD) M
-- ON M.VIEW = B.VIEWS
-- ORDER BY F.FILE_ID DESC
